### ISSUE TITLE
Filename length

### ISSUE THREAD

**Issue by dajwahl** [katerinaziot/PM4Sand_drivers_auto#3]
This is a bit odd, but the filenames can get cutoff when producing results from the drivers.  It appears the limit is 123 characters including folder names.  The limit in Windows 10 is 260 characters, so this appears to be FLAC specific.

**Comment by katerinaziot** [comment]
Commited 2 requests. Good catch. Issue resolved - thank you Doug.

**Comment by katerinaziot** [comment]
Commited 2 requests. Good catch. Issue resolved - thank you Doug.
